/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './platform/routes/root'
import { Route as platformRoutesIndexRouteImport } from './platform/routes/index'
import { Route as moduleDashboardDashboardDotrouteRouteImport } from './module/dashboard/dashboard.route'
import { Route as moduleMapMapDotrouteRouteImport } from './module/map/map.route'
import { Route as moduleDashboardRunsDotrouteRouteImport } from './module/dashboard/runs.route'

const platformRoutesIndexRoute = platformRoutesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const moduleDashboardDashboardDotrouteRoute =
  moduleDashboardDashboardDotrouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const moduleMapMapDotrouteRoute = moduleMapMapDotrouteRouteImport.update({
  id: '/cadastre',
  path: '/cadastre',
  getParentRoute: () => moduleDashboardDashboardDotrouteRoute,
} as any)
const moduleDashboardRunsDotrouteRoute =
  moduleDashboardRunsDotrouteRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => moduleDashboardDashboardDotrouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof platformRoutesIndexRoute
  '/dashboard': typeof moduleDashboardDashboardDotrouteRouteWithChildren
  '/dashboard/cadastre': typeof moduleMapMapDotrouteRoute
  '/dashboard/runs': typeof moduleDashboardRunsDotrouteRoute
}
export interface FileRoutesByTo {
  '/': typeof platformRoutesIndexRoute
  '/dashboard': typeof moduleDashboardDashboardDotrouteRouteWithChildren
  '/dashboard/cadastre': typeof moduleMapMapDotrouteRoute
  '/dashboard/runs': typeof moduleDashboardRunsDotrouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof platformRoutesIndexRoute
  '/dashboard': typeof moduleDashboardDashboardDotrouteRouteWithChildren
  '/dashboard/cadastre': typeof moduleMapMapDotrouteRoute
  '/dashboard/runs': typeof moduleDashboardRunsDotrouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/dashboard/cadastre' | '/dashboard/runs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/dashboard/cadastre' | '/dashboard/runs'
  id:
    '__root__' | '/' | '/dashboard' | '/dashboard/cadastre' | '/dashboard/runs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  platformRoutesIndexRoute: typeof platformRoutesIndexRoute
  moduleDashboardDashboardDotrouteRoute: typeof moduleDashboardDashboardDotrouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof platformRoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof moduleDashboardDashboardDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cadastre': {
      id: '/dashboard/cadastre'
      path: '/cadastre'
      fullPath: '/dashboard/cadastre'
      preLoaderRoute: typeof moduleMapMapDotrouteRouteImport
      parentRoute: typeof moduleDashboardDashboardDotrouteRoute
    }
    '/dashboard/runs': {
      id: '/dashboard/runs'
      path: '/runs'
      fullPath: '/dashboard/runs'
      preLoaderRoute: typeof moduleDashboardRunsDotrouteRouteImport
      parentRoute: typeof moduleDashboardDashboardDotrouteRoute
    }
  }
}

interface moduleDashboardDashboardDotrouteRouteChildren {
  moduleMapMapDotrouteRoute: typeof moduleMapMapDotrouteRoute
  moduleDashboardRunsDotrouteRoute: typeof moduleDashboardRunsDotrouteRoute
}

const moduleDashboardDashboardDotrouteRouteChildren: moduleDashboardDashboardDotrouteRouteChildren =
  {
    moduleMapMapDotrouteRoute: moduleMapMapDotrouteRoute,
    moduleDashboardRunsDotrouteRoute: moduleDashboardRunsDotrouteRoute,
  }

const moduleDashboardDashboardDotrouteRouteWithChildren =
  moduleDashboardDashboardDotrouteRoute._addFileChildren(
    moduleDashboardDashboardDotrouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  platformRoutesIndexRoute: platformRoutesIndexRoute,
  moduleDashboardDashboardDotrouteRoute:
    moduleDashboardDashboardDotrouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
